### ISSUE TITLE
The algorithm should be able to detect whether the edit was rollbacked or reviewed

### ISSUE THREAD

**Issue by Alex-Rybak** [sfedia/ru-wikt-vandalism-detection#1]

**Comment by sfedia** [comment]
I suggest compare the diff bytes count of the edit and any of subsequent edits. Rollback edit of an edit with `diff_bytes_count=X` should then have `diff_bytes_count=-X`
<img width="1174" alt="Screenshot 2024-11-10 at 17 21 47" src="https://github.com/user-attachments/assets/3e83cd01-0989-497b-908d-a96c4a61ed50">

**Comment by sfedia** [comment]
On the other hand, if an edit was reviewed, it's easy to know this from MediaWiki API. This one is a straightforward task.

**Comment by sfedia** [comment]
> I suggest comparing the diff bytes count of the edit and any of subsequent edits. Rollback edit of an edit with `diff_bytes_count=X` should then have `diff_bytes_count=-X` <img alt="Screenshot 2024-11-10 at 17 21 47" width="1174" src="https://private-user-images.githubusercontent.com/16120239/384706322-3e83cd01-0989-497b-908d-a96c4a61ed50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTYxMDMsIm5iZiI6MTczMTI1NTgwMywicGF0aCI6Ii8xNjEyMDIzOS8zODQ3MDYzMjItM2U4M2NkMDEtMDk4OS00OTdiLTkwOGQtYTk2YzRhNjFlZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE2MjMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMjg4YTM1NTk3ZWE1M2MwNzE0YWYwNDhmODdlZDNjYTI3NTkxNDQ5ZmI5ODE2ZDg4MTk3NWQyOTI3MTEwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._-JP-xpHwbmRHURRUfr3GnMDD2ZN6hC0DlG5DStQQjc">

This method may lead to collisions, and also we need to carefully consider cases when the source edit consists of multiple diffs, or rollback edit consists of multiple diffs, or they both do.
